<?php

namespace Database\Factories;

use App\Models\ParishRegistration;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\ParishRegistration>
 */
class ParishRegistrationFactory extends Factory
{
    protected $model = ParishRegistration::class;

    public function definition(): array
    {
        $type = fake()->randomElement(['individual', 'family']);
        $dob = fake()->dateTimeBetween('-75 years', '-18 years');

        return [
            'registration_type' => $type,
            'member_id' => null, // auto-generated by model boot() if not provided
            'full_name' => fake()->name(),
            'date_of_birth' => $dob->format('Y-m-d'),
            'gender' => fake()->randomElement(['male', 'female', 'other']),
            'nationality' => fake()->boolean(65) ? fake()->country() : null,
            'occupation' => fake()->boolean(65) ? fake()->jobTitle() : null,
            'address_line1' => fake()->streetAddress(),
            'address_line2' => fake()->boolean(40) ? fake()->secondaryAddress() : null,
            'city' => fake()->city(),
            'postcode' => fake()->postcode(),
            'partner_name' => $type === 'family' ? fake()->name() : null,
            'phone' => fake()->phoneNumber(),
            'email' => fake()->unique()->safeEmail(),
            'contact_by_phone' => fake()->boolean(60),
            'contact_by_email' => fake()->boolean(70),
            'consent_confirmed' => true,
            'signature' => fake()->name(),
            'signed_date' => now()->subDays(fake()->numberBetween(0, 30))->toDateString(),
        ];
    }
}

